/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-fixed-dim': '#bec6e0',
        'tertiary': '#000000',
        'error': '#ba1a1a',
        'surface-variant': '#e0e3e5',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#001f26',
        'on-tertiary-fixed': '#001f26',
        'surface-container-highest': '#e0e3e5',
        'inverse-on-surface': '#eff1f3',
        'outline': '#76777d',
        'on-surface-variant': '#45464d',
        'on-secondary-fixed-variant': '#003ea8',
        'on-secondary-fixed': '#00174b',
        'secondary-fixed': '#dbe1ff',
        'on-error': '#ffffff',
        'on-surface': '#191c1e',
        'inverse-surface': '#2d3133',
        'primary-fixed': '#dae2fd',
        'on-primary-fixed-variant': '#3f465c',
        'surface-bright': '#f7f9fb',
        'primary-container': '#131b2e',
        'inverse-primary': '#bec6e0',
        'tertiary-fixed': '#acedff',
        'error-container': '#ffdad6',
        'on-primary': '#ffffff',
        'on-background': '#191c1e',
        'secondary-fixed-dim': '#b4c5ff',
        'background': '#f7f9fb',
        'on-secondary': '#ffffff',
        'on-error-container': '#93000a',
        'surface-container-high': '#e6e8ea',
        'on-primary-container': '#7c839b',
        'outline-variant': '#c6c6cd',
        'on-tertiary-fixed-variant': '#004e5c',
        'on-secondary-container': '#fefcff',
        'tertiary-fixed-dim': '#4cd7f6',
        'surface-container': '#eceef0',
        'primary': '#000000',
        'secondary': '#0051d5',
        'surface-container-low': '#f2f4f6',
        'on-primary-fixed': '#131b2e',
        'surface-tint': '#565e74',
        'surface-container-lowest': '#ffffff',
        'surface-dim': '#d8dadc',
        'secondary-container': '#316bf3',
        'on-tertiary-container': '#0090a9',
        'surface': '#f7f9fb',
        'success': '#00A86B',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'unit-xl': '48px',
        'margin-mobile': '16px',
        'unit-md': '16px',
        'unit-xs': '4px',
        'margin-desktop': '40px',
        'unit-sm': '8px',
        'unit-lg': '24px',
        'container-max': '1440px',
        'gutter': '24px',
      },
      fontFamily: {
        geist: ['Geist', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['14px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '14px', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      maxWidth: {
        'container-max': '1440px',
      },
      animation: {
        'fade-in-up': 'fadeInUp 0.8s ease-out forwards',
        'progress': 'progress 1.5s ease-out forwards',
        'spin-slow': 'spin 1s linear infinite',
      },
      keyframes: {
        fadeInUp: {
          from: { opacity: '0', transform: 'translateY(20px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        progress: {
          '0%': { strokeDasharray: '0 100' },
        },
      },
    },
  },
  plugins: [],
}
